=begin
#Selling Partner API for Sellers

#The [Selling Partner API for Sellers](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) (Sellers API) provides essential information about seller accounts, such as:  - The marketplaces a seller can list in - The default language and currency of a marketplace - Whether the seller has suspended listings  Refer to the [Sellers API reference](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) for details about this API's operations, data types, and schemas.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.61
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::SellersApiModel::MarketplaceLevelAttributes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MarketplaceLevelAttributes' do
  before do
    # run before each test
    @instance = AmzSpApi::SellersApiModel::MarketplaceLevelAttributes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MarketplaceLevelAttributes' do
    it 'should create an instance of MarketplaceLevelAttributes' do
      expect(@instance).to be_instance_of(AmzSpApi::SellersApiModel::MarketplaceLevelAttributes)
    end
  end
  describe 'test attribute "marketplace"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "store_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "listing_status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["ACTIVE", "INACTIVE"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.listing_status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "selling_plan"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["PROFESSIONAL", "INDIVIDUAL"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.selling_plan = value }.not_to raise_error
      # end
    end
  end

end
